FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY *.go ./

RUN go mod init rinha-load-balancer
RUN go mod tidy

RUN CGO_ENABLED=0 go build -o /app/load-balancer .

FROM scratch

WORKDIR /app

COPY --from=builder /app/load-balancer .

EXPOSE 9999

CMD ["/app/load-balancer"]
